### ISSUE TITLE
legend margin

### ISSUE THREAD

**Issue by createandbuild** [wwsalmon/sota.js#53]
![image](https://user-images.githubusercontent.com/33373263/83554997-9bfc0780-a4db-11ea-97f1-dbea994657ac.png)

**Comment by wwsalmon** [comment]
what's the issue?

**Comment by createandbuild** [comment]
The legend spills over; see the cut off "ys" on the left of the image? That's supposed to be "yes, always" since the pie chart has four groups but it's spilling over

**Comment by wwsalmon** [comment]
aha, jank i'll take a look
