### ISSUE TITLE
add sorted parameter for pieChart

### ISSUE THREAD

**Issue by createandbuild** [wwsalmon/sota.js#55]
![image](https://user-images.githubusercontent.com/33373263/83695729-a47e3c00-a5c8-11ea-8e12-8430647795b6.png)

the orders for colors/groups are wrong/inconsistent with the legend

**Comment by createandbuild** [comment]
Only for some of them though. Hm weird

**Comment by createandbuild** [comment]
some of them go clock-wise while some of them go counter clock-wise (everything in discipline section)
![image](https://user-images.githubusercontent.com/33373263/83696783-5a4a8a00-a5cb-11ea-86c7-0c9c9f2994ba.png)
. This is not a huge deal
![image](https://user-images.githubusercontent.com/33373263/83696757-43a43300-a5cb-11ea-9c56-d24b1854d257.png)
![image](https://user-images.githubusercontent.com/33373263/83696791-5f0f3e00-a5cb-11ea-8cdb-2cb31bd72b34.png)

**Comment by createandbuild** [comment]
Also the first group should be at the top (example below)
![image](https://user-images.githubusercontent.com/33373263/83697332-b661de00-a5cc-11ea-98e0-2edb4797c57b.png)

**Comment by wwsalmon** [comment]
This is intentional behavior right now, we talked about it before...what would be a useful feature is a `sorted` parameter for pieChart

**Comment by wwsalmon** [comment]
implemented, just pass `sorted=false` param, i.e. `sota.pieChart({selector: "#module-politics-informed-d3", dataFile: "assets/data/politics/informed", sorted: false});`
